# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-09 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ext', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='created',
        ),
        migrations.RemoveField(
            model_name='pdf',
            name='modified',
        ),
        migrations.AddField(
            model_name='pdf',
            name='id',
            field=models.AutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pdf',
            name='author',
            field=models.CharField(max_length=200),
        ),
    ]
