# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-09 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ext', '0002_auto_20180609_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='Creator',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='Producer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='keywords',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
