# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-09 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ext', '0003_auto_20180609_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
